files:
  - source: /src/main/resources/assets/createfactorycontroller/lang/en_us.json
    translation: /src/main/resources/assets/createfactorycontroller/lang/%locale_with_underscore%.json
  - source: /manual/l10n/*.pot
    translation: /manual/l10n/%file_name%.%two_letters_code%.po
  - source: /manual/l10n/attributes.yaml
    translation: /manual/l10n/attributes.%two_letters_code%.yaml
