pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = mod_id

// Create: Higher Logistics Patch and Create: Logistics Control each live in their own repository and are bundled into
// this mod via Jar-in-Jar.
includeBuild('../create_higher_logistics_patch')
includeBuild('../create_logistics_control')