= Create: Factory Controller Manual

Create: Factory Controller provides a block called the "`factory controller`", which allows you to place factory gauges and other components on a virtual board stored inside the block. Factory gauges placed in factory controllers also receive many functional enhancements.

You do not need to read this manual in full to use the mod. The manual serves to provide a reference to the features of the mod, especially to those that are difficult to explain fully in the UI.

:mod-version: 1.1.1

This manual corresponds to version {mod-version} of the mod. Information may be incorrect for other versions.

[#table-of-contents]
== {toc-title}

[#manual-toc]
. xref:dashboard.adoc[Dashboard]
. xref:components.adoc[Components]
.. xref:factory-gauge.adoc[Factory Gauge]
.. xref:electron-tube.adoc[Electron Tube]
.. xref:redstone-link.adoc[Redstone Link]
. xref:display-link.adoc[Display Link]
. xref:blueprint.adoc[Blueprint]
. xref:production-orders.adoc[Production Orders]
