# Container to ease building the manual

FROM docker.io/library/ruby:3.4-alpine3.24

WORKDIR /work/manual

RUN apk add --no-cache git icu-libs icu-data-full po4a perl-yaml-tiny

ADD Gemfile Gemfile.lock ./

RUN <<END
apk add --no-cache build-base
bundle install
apk del --no-cache build-base
git config --system --add safe.directory /work
END

CMD ["rake"]
