# Container to ease building the manual

FROM docker.io/library/ruby:3.4-alpine3.24

WORKDIR /work

RUN apk add --no-cache po4a perl-yaml-tiny

ADD Gemfile Gemfile.lock ./

RUN <<END
apk add --no-cache build-base
bundle install
apk del --no-cache build-base
END

CMD ["rake"]
