source 'https://rubygems.org'

gem 'asciidoctor', '~> 2.0.26'
gem 'asciidoctor-html5s', '~> 0.5.1'

gem 'rake', '~> 13.4.2'
gem 'nokogiri', '~> 1.19.4'

gem 'twitter_cldr', '~> 6.14'
  gem 'bigdecimal', '~> 4.1.2'
gem 'font-awesome-sass', '~> 6.7.2'
