source 'https://rubygems.org'

gem 'asciidoctor', '~> 2.0.26'
gem 'asciidoctor-html5s', '~> 0.5.1'

gem 'rake', '~> 13.4.2'
gem 'nokogiri', '~> 1.19.4'
gem 'ffi-icu', '~> 0.6.1'

gem 'font-awesome-sass', '~> 6.7.2'
