require 'rake/clean'
require 'erb'
require 'yaml'
require 'asciidoctor'
require 'asciidoctor-html5s'
require 'nokogiri'
require 'font-awesome-sass'
require_relative 'lib/replacements'
require_relative 'lib/util'

CLOBBER << 'build'

# Get languages from po4a config
LANGS = File.readlines("l10n/po4a.cfg")
  .find{|x| x =~ /^\[po4a_langs\]/ }
  .split(?])[1].scan(/[\w_-]+/)

LANGS.prepend 'en'
def LANGS.default() first end


# Define tasks to build each and all languages
task default: :build
desc "Build HTML for all languages"
task :build

LANGS.each do |lang|
  task :build => :"build_#{lang}"
  desc "Build HTML of language #{lang}"
  task :"build_#{lang}" => %i(assets po4a:translate) do
    build_lang(lang)
  end
end

namespace 'po4a' do
  desc "Update translation files"
  task :update do
    cd 'l10n' do
      sh *%W(po4a --no-translations po4a.cfg)
    end
  end

  desc "Generated translated documents"
  task :translate do
    cd 'l10n' do
      sh *%W(po4a --no-update po4a.cfg)
    end
  end
end


# Memoized variables
layout = nil
lang_attributes = nil
lang_manual_toc = nil

# Build HTML of a language
def build_lang(lang)
  layout ||= ERB.new File.read 'src/_layout.erb'

  # Translatable attributes
  lang_attributes ||= Hash.new do |hash, lang|
    local = Util.flatten_hash YAML.load_file "l10n/attributes.#{lang}.yaml" rescue nil if lang != LANGS.default
    fallback = Util.flatten_hash YAML.load_file "l10n/attributes.yaml"
    lang_attributes[lang] = fallback.merge local || {}
  end
  attributes = lang_attributes[lang]

  adoc_options = {
    safe: :safe,
    backend: 'html5s',
    parse: true,
    standalone: false,
    attributes: {
      'imagesdir' => '../images',
    }.merge(attributes.map{|k, v| ["#{k}@", v]}.to_h),
  }

  # Read index.adoc for a TOC of the entire manual
  lang_manual_toc ||= Hash.new do |hash, lang|
    source_path = ["translated/#{lang}/index.adoc", 'src/index.adoc'].find(&File.method(:exist?))
    doc = Asciidoctor.load_file source_path, adoc_options
    toc = doc.find_by(id: 'manual-toc')[0].convert
    lang_manual_toc[lang] = Util.html_strip toc, layers: 2
  end
  manual_toc = lang_manual_toc[lang]

  verbose(false) { mkdir_p "build/#{lang}" }

  Dir.glob('[^_]*.adoc', base: 'src').each do |source|
    source_path = lang == LANGS.default ? "src/#{source}" : "translated/#{lang}/#{source}"
    source_basename = source.sub(/\.adoc$/, '')
    output_path = "build/#{lang}/#{source_basename}.html"

    authors = Util.git_file_authors("src/#{source}")
    translators = lang == LANGS.default ? [] :
      authors - Util.git_file_authors("l10n/#{source_basename}.#{lang}.po")

    title = nil
    content = nil
    page_toc = nil
    no_translation = false

    if File.exist? source_path
      puts "Generate page #{output_path}" if verbose
      document = Asciidoctor.load_file source_path, adoc_options

      title = document.title
      content = Util.cache_id_images(document.convert, output_path)

      page_toc = document.converter.convert document, 'outline', toclevels: 2
      page_toc = Util.html_strip page_toc, strip_class: true

    else
      puts "Generate missing translation page #{output_path}" if verbose
      no_translation = true
    end

    html = layout.result LayoutContext.new(
      title: title,
      content: content,
      authors: authors,
      translators: translators,
      attributes: attributes,
      language: lang,
      languages: LANGS,
      manual_toc: manual_toc,
      page_toc: page_toc,
      no_translation: no_translation,
      output_filename: "#{source_basename}.html",
      output_path: output_path,
    ).binding

    File.write output_path, html
  end
end

# Context object to provide variables and methods to the ERB template
LayoutContext = Struct.new *%i(
  title content attributes
  authors translators
  language languages
  manual_toc page_toc
  no_translation
  output_filename output_path
) do
  def binding() Kernel.binding end
  def h(value) ERB::Util.html_escape(value) end
  def t(key) attributes[key] || key end
  def lang_name(lang) Util.get_language_endonym(lang) end
  def attach_cache_id(path) Util.add_cache_id(path, output_path) end
end


# Define assets to be copied to `build`
assets = {
  'build/style.css' => 'src/style.css',
  'build/images' => 'src/images',
  'build/fonts/fa-solit-900.woff2' => "#{FontAwesome::Sass.fonts_path}/font-awesome/fa-solid-900.woff2",
}

desc 'Copy static assets'
task :assets => assets.keys

assets.each do |t, s|
  file t => s do |task|
    verbose(false) { mkdir_p File.dirname(task.name) }
    if File.directory? task.prereqs[0]
      cp_lr task.prereqs[0], File.dirname(task.name), remove_destination: true
    else
      cp task.prereqs[0], File.dirname(task.name)
    end
  end
end
