= Manual

User manual of the mod.

[NOTE]
To translate the documents, go to link:https://weblate.fiveyellowmice.com/engage/create-factory-controller/[Weblate].

Directory structure:

* `src/`
** `\*.adoc`: Source documents, translated and built to `build/$lang/*.html`. Written in English.
** `style.css`, `images/`: Static assets, copied to `build/`.
** `_layout.erb`: HTML template for all documents.

* `l10n/`
** `po4a.cfg`: po4a config
** `attributes.yaml`: Translatable attributes common to all documents, English.
** `attributes.$lang.yaml`: Translations of `attributes.yaml`.
** `*.pot`: Translation template for each document, generated by po4a.
** `*.$lang.po`: Translation for each document.

* `lib/`: Ad-hoc Ruby libraries, extensions to Asciidoctor, etc.
* `translated/$lang/`: Translated documents generated by po4a.
* `build/`: Built web pages.
* `vendor/`: Dependencies.

== Build

Install:

* Ruby ≥ 3.4
* Ruby Bundler
* Node.js ≥ 24
* po4a ≥ 0.74

[source,sh]
----
bundle config set path vendor/bundle
bundle install
bundle exec rake build
----

Alternatively, use a Docker container:

[source,sh]
----
docker run --rm -v .:/work ghcr.io/nbcss/create-factory-controller/manual-builder:latest rake build
----

== Writing Source Documents

Update translation files after making changes: `bundle exec rake po4a:update`
